tasks:
  - command: |
      cd v1
      npm i -g saucectl
      if [[ -z "$BUILD" ]] && [[ -z "$REGION" ]]; then
        saucectl run
      elif [[ -z "$BUILD" ]]; then
        saucectl run --region $REGION
      elif [[ -z "$REGION" ]]; then
        saucectl run --build $BUILD
      else
        saucectl run --region $REGION --build $BUILD
      fi
