version: 2.1
orbs:
  saucectl: saucelabs/saucectl-run@3.0.0

jobs:
  test-cypress-v1:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - saucectl/saucectl-run:
          working-directory: v1

workflows:
  version: 2
  default_workflow:
    jobs:
      - test-cypress-v1
