version: 2.1
orbs:
  saucectl: saucelabs/saucectl-run@1.0.0

jobs:
  test-cypress-v1alpha:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - saucectl/saucectl-run:
          working-directory: v1alpha
  test-cypress-v1:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - saucectl/saucectl-run:
          working-directory: v1

workflows:
  version: 2
  default_workflow:
    jobs:
      - test-cypress-v1alpha
      - test-cypress-v1
