version: 2.1
orbs:
  saucectl: saucelabs/saucectl-run@1.0.0

jobs:
  test-cypress:
    docker:
      - image: circleci/node:12.21
    environment:
      BUILD_ID: $CIRCLE_BUILD_NUM
      BUILD_ENV: CircleCI
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - saucectl/saucectl-run:
          testing-environment: docker
      - saucectl/saucectl-run:
          testing-environment: sauce

workflows:
  version: 2
  default_workflow:
    jobs:
      - test-cypress
