apiVersion: v1alpha
kind: cypress
sauce:
  region: us-west-1
  concurrency: 10 # Controls how many suites are executed at the same time.
  metadata:
    tags:
      - e2e
      - release team
      - other tag
    build: Github Run $GITHUB_RUN_ID
cypress:
  version: 9.7.0 # See https://docs.saucelabs.com/web-apps/automated-testing/cypress/#supported-testing-platforms for a list of supported versions.
  configFile: "cypress.json"  # We determine related files based on the location of the config file.

rootDir: ./
suites:
  - name: "Chrome on Windows"
    browser: "chrome"
    platformName: "Windows 11"
    screenResolution: "1920x1080"  # (optional)
    config:
      env:
        grepTags: "@smoke"
      testFiles: [ "**/*.*" ] # Cypress native glob support.

# Controls what artifacts to fetch when the suites have finished.
artifacts:
  download:
    when: always
    match:
      - console.log
    directory: ./artifacts/
npm:
  dependencies:
    - cypress-grep
