apiVersion: v1
kind: cypress
# https://docs.saucelabs.com/web-apps/automated-testing/cypress/yaml/
defaults:
  mode: sauce
sauce:
  region: us-west-1
  concurrency: 2 # Controls how many suites are executed at the same time.
  metadata:
    tags:
      - cucumber
      - example repo
    # build: Github Run $GITHUB_RUN_ID
docker:
  # Affects how test files are transferred to the docker container when using the docker mode.
  fileTransfer: copy # Choose between mount|copy.
cypress:
  version: 10.3.1 # See https://docs.saucelabs.com/web-apps/automated-testing/cypress/ for a list of supported versions.
  configFile: "cypress.config.js"  # We determine related files based on the location of the config file.
# Controls what files are available in the context of a test run (unless explicitly excluded by .sauceignore).
rootDir: ./
suites:
  - name: "Chrome"
    browser: "chrome"
    platformName: "Windows 11"
    config:
      specPattern: [ "cypress/e2e/**/*.feature" ] # Cypress native glob support.

# Controls what artifacts to fetch when the suite on Sauce Cloud has finished.
artifacts:
  download:
    when: never
    match:
      - console.log
    directory: ./artifacts/

# https://docs.saucelabs.com/web-apps/automated-testing/cypress/yaml/#npm
# Any additional dependencies need to be configured here so that they are packaged on demand.
# These dependencies are picked up from the node_modules folder, so they need to be already installed locally.
# Select only what you truly need to get your tests running, as installing dependencies takes time.
npm:
  dependencies:
    - "@badeball/cypress-cucumber-preprocessor"
    - "@cypress/webpack-preprocessor"
    - "webpack"
